language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - protobuf-compiler
    - os: osx
      osx_image: xcode8

env:
  global:
    - XGBOOST_VERSION=42
    - LIBHDFS_DIR=$HOME/libhdfs-dev
    - HADOOP_VERSION="2.6.0-cdh5.5.0"
    - SPARK_VERSION=2.1.0
    - SCALA_VERSION=2.10.6

install:
  - python --version
  - if [ ! -z `find $LIBHDFS_DIR -prune -empty` ]; then python ./install_libhdfs.py; fi
  - cd xgboost
  - mkdir -p lib/native
  - cp $LIBHDFS_DIR/libhdfs.a lib/native
  - cp $LIBHDFS_DIR/hdfs.h dmlc-core/include/
  - sed -i -e 's/<hdfs.h>/"hdfs.h"/g' dmlc-core/src/io/hdfs_filesys.h
  # TODO: submit upstream.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i -e 's/-rpath=$(LIBJVM)/-rpath,$(LIBJVM)/' dmlc-core/make/dmlc.mk; fi
  - cp ../config_${TRAVIS_OS_NAME}.mk config.mk
  - cd jvm-packages
  - mvn -q -B versions:set -DnewVersion=${XGBOOST_VERSION}
  # versions:update-property only updates properties which define
  # artifact versions, therefore we have to resort to sed.
  - sed -i -e 's/<scala.binary.version>2.11/<scala.binary.version>'${SCALA_VERSION%.*}'/' pom.xml
  - mvn -q versions:update-property -Dproperty=scala.version -DnewVersion="[$SCALA_VERSION]"
  - mvn -q versions:update-property -Dproperty=spark.version -DnewVersion="[$SPARK_VERSION]"
  - HADOOP_HOME=. mvn -q install -pl :xgboost4j,:xgboost4j-spark -DskipTests -Dmaven.test.skip

script:
  - HADOOP_HOME=. mvn -q package -pl :xgboost4j,:xgboost4j-spark

cache:
  directories:
    - $HOME/.m2
    - $LIBHDFS_DIR

deploy:
  provider: releases
  api_key:
    secure: tCV+MeGvnSGoVYuf7QLnRUMHPNUdu6H0lsYNjY6r1e05SsmaUZNiZJKoRdw+wv/aIZI3sqJIfd3TviVZoGwcRQnTxsKgA3r+sQWt2mu3ABojynkgyyclIrIHyUhjUtyXAaRDx07GDgMflLDQ3cQEE8f8/7gLQftXdehdM64hGEuw7YSgPOh3sq/N8H48pIlPffSJb4zVGrpFhpLsfOPurXyeifhHvcPq7kvcAVxJA7BsnvN1rh9ORZe7LBtfNb0m20rGEc+t5t4SKPHlRjuVAc7RGjEzRwJuNLYB6o8kNJgHAu+E6VjryheuwfVwOQ0ez7QpkdpClwfGFutuOELOTCqEvh6QTlwc0Dz5acfQ+DZqhP/DFUKDTntXuk7wrIPBMDgR9MOduXGYojfQeQJzp2E/vuZ1aSq21+qHy0HXLQTs3fYTw9gmg/oz6o/EwFKy9qdcgH3Dl6Ay/XWw4JooL3t7hasOFjc8EObP2+39pOcl+TiLpEzGgSzPNqfHb+PpE2jrfip5tc1wcR3EHYCHmdrAZBhL6oUeAEZ5pwulcBBBHrbApN8FoFtopcIAht3hdbbK0NhbNzL2ZxyAbsmZHQqV9BnoVrfOSrnK0uFuht2Q4xj0j9q3ianCrHOOEnYwo+6993OEEMLtRPxIN09mZuK43kuKIUGc0Qmv9hQxMr4=
  file:
    - $TRAVIS_BUILD_DIR/xgboost/jvm-packages/xgboost4j-spark/target/xgboost4j-spark-${XGBOOST_VERSION}.jar
    - $TRAVIS_BUILD_DIR/xgboost/jvm-packages/xgboost4j/target/xgboost4j-${XGBOOST_VERSION}.jar
  on:
    tags: true
