language: java

matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      services:
        - docker
    - os: osx
      osx_image: xcode8

env:
  global:
    - XGBOOST_VERSION=0.7-criteo-20171117
    - LIBHDFS_DIR=$HOME/libhdfs-dev
    - HADOOP_VERSION=2.6.0-cdh5.5.0
    - SCALA_VERSION=2.10.6
    - SPARK_VERSION=2.1.0

before_install:
  - git submodule foreach --recursive git pull origin master
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/install.sh; fi


script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/test_and_package.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run
            -e XGBOOST_VERSION
            -e LIBHDFS_DIR
            -e HADOOP_VERSION
            -e SCALA_VERSION
            -e SPARK_VERSION
            -e TRAVIS_OS_NAME
            -v `pwd`:/xgboost-jars:rw
            centos:centos6
            /bin/bash -c "bash -xe /xgboost-jars/travis/docker.sh";
    fi

cache:
  directories:
    - $LIBHDFS_DIR

deploy:
  provider: releases
  api_key:
    secure: tCV+MeGvnSGoVYuf7QLnRUMHPNUdu6H0lsYNjY6r1e05SsmaUZNiZJKoRdw+wv/aIZI3sqJIfd3TviVZoGwcRQnTxsKgA3r+sQWt2mu3ABojynkgyyclIrIHyUhjUtyXAaRDx07GDgMflLDQ3cQEE8f8/7gLQftXdehdM64hGEuw7YSgPOh3sq/N8H48pIlPffSJb4zVGrpFhpLsfOPurXyeifhHvcPq7kvcAVxJA7BsnvN1rh9ORZe7LBtfNb0m20rGEc+t5t4SKPHlRjuVAc7RGjEzRwJuNLYB6o8kNJgHAu+E6VjryheuwfVwOQ0ez7QpkdpClwfGFutuOELOTCqEvh6QTlwc0Dz5acfQ+DZqhP/DFUKDTntXuk7wrIPBMDgR9MOduXGYojfQeQJzp2E/vuZ1aSq21+qHy0HXLQTs3fYTw9gmg/oz6o/EwFKy9qdcgH3Dl6Ay/XWw4JooL3t7hasOFjc8EObP2+39pOcl+TiLpEzGgSzPNqfHb+PpE2jrfip5tc1wcR3EHYCHmdrAZBhL6oUeAEZ5pwulcBBBHrbApN8FoFtopcIAht3hdbbK0NhbNzL2ZxyAbsmZHQqV9BnoVrfOSrnK0uFuht2Q4xj0j9q3ianCrHOOEnYwo+6993OEEMLtRPxIN09mZuK43kuKIUGc0Qmv9hQxMr4=
  file:
    - xgboost4j-$XGBOOST_VERSION-$TRAVIS_OS_NAME.jar
    - xgboost4j-spark-$XGBOOST_VERSION.jar
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
