name: XGBoost-Build

on: [push]

env:
  HADOOP_VERSION: 2.6.0-cdh5.5.0
  SPARK_VERSION: 2.4.1
  SCALA_VERSION: 2.11.12
  SCALA_BINARY_VERSION: 2.11
  XGBOOST_VERSION_DMLC: 1.1.0
  XGBOOST_BASE_VERSION: 1.1.0-criteo-20200807-071ef500

jobs:
  build-jvm:
    name: Build JVM on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Adapt pom.xml files
        run: |
          python install_xgboost.py

      - uses: warrenbuckley/Setup-MSBuild@v1
        if: runner.os == 'Windows'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('./xgboost/jvm-packages/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install JVM packages (Linux / MacOs)
        if: runner.os == 'Linux' || runner.os == 'macOs'
        run: |
          cd xgboost/jvm-packages
          mvn package -q -pl xgboost4j,xgboost4j-spark -DskipTests -Psources

      - name: Install JVM packages (Windows)
        if: runner.os == 'Windows'
        run: |
          cd xgboost/jvm-packages
          mvn package -q -pl xgboost4j,xgboost4j-spark -DskipTests

      - name: Renaming file - Windows
        if: runner.os == 'Windows'
        run: |
          cd xgboost/jvm-packages
          move xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.jar xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}-win64.jar
          move pom.xml xgboost-jvm_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.pom

      - name: Renaming file - Linux
        if: runner.os == 'Linux'
        run: |
          cd xgboost/jvm-packages
          mv xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.jar xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}-linux.jar
          mv pom.xml xgboost-jvm_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.pom

      - name: Renaming file - MacOs
        if: runner.os == 'macOs'
        run: |
          cd xgboost/jvm-packages
          mv xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.jar xgboost4j/target/xgboost4j_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}-osx.jar
          mv pom.xml xgboost-jvm_${{env.SCALA_BINARY_VERSION }}-${{env.XGBOOST_BASE_VERSION}}.pom

      - uses: ncipollo/release-action@v1
        if: contains(github.ref, 'tags/')
        with:
          allowUpdates: true
          artifacts: "./xgboost/jvm-packages/xgboost4j/target/*.jar,./xgboost/jvm-packages/xgboost4j-spark/target/*.jar,./xgboost/jvm-packages/*.pom"
          token: ${{ secrets.GITHUB_TOKEN }}
